version: '2'
services:
  web:
    build:
      context: .
      args:
          CDS_AGGREGATE: https://caf-shib2ops.ca/CoreServices/caf_metadata_signed_sha256.xml
    command: '/start.sh'
    ports:
      - "80:80"
    
      
